<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customers')->upsert([
            [
                'id' => 1,
                'customer_name' => 'Arena Phone BD. Ltd',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Ananna Villa, (4th Floor), Road # 23/A, Gulshan-01, Dhaka-1212.',
                'bin_number' => '000996906',
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md.Al Amin Farazi',
                'commercial_contact_designation' => 'Manager Business Development',
                'commercial_contact_email' => NULL,
                'commercial_contact_phone' => '01844054139',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:27:41',
                'updated_at' => '2025-12-28 15:27:41',
            ],
            [
                'id' => 2,
                'customer_name' => 'Monico Technologies Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Monico Bhaban, Plot # 26-27, Ring Road, Adabor, Dhaka-1207.',
                'bin_number' => '000090681',
                'po_number' => '1285 ,1288 (ColoDHK/2019/01)',
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Mr. Khalid Bin Anowar',
                'commercial_contact_designation' => 'AGM Business Development',
                'commercial_contact_email' => 'khalid@finder-Ibs.com',
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:29:52',
                'updated_at' => '2025-12-28 15:29:52',
            ],
            [
                'id' => 3,
                'customer_name' => 'Mir Ceramic Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => '312 Sonargaon Road, RK Tower (2nd Floor), Dhaka-1205.',
                'bin_number' => NULL,
                'po_number' => 'MirCloud_MirCeramic_042019',
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Kazi Mehedi Hasan',
                'commercial_contact_designation' => 'Sr. Executive',
                'commercial_contact_email' => 'mehedi.it@mirceramic.com',
                'commercial_contact_phone' => '01322841002',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:31:19',
                'updated_at' => '2025-12-28 15:31:19',
            ],
            [
                'id' => 4,
                'customer_name' => 'Portonics Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Navana HR Tower, Level 8 (Tower - 1), Plot - 410, Bir Uttam Mir Showkat Sarak, Tejgaon I/A, Dhaka-1208',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Mr. Sadiqur Rahman',
                'commercial_contact_designation' => 'CTO',
                'commercial_contact_email' => 'sadiq@portonics.com',
                'commercial_contact_phone' => '01755649721',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:32:19',
                'updated_at' => '2025-12-28 15:32:19',
            ],
            [
                'id' => 5,
                'customer_name' => 'JadeWits Technologies Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Flat 10/A (Top Floor), House 5/10, Block E, Lalmatia, Dhaka-1207',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Nafiul Alam Chowdhury',
                'commercial_contact_designation' => 'Managing Director',
                'commercial_contact_email' => 'nafi@jadewits.com',
                'commercial_contact_phone' => '01713204715',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:33:22',
                'updated_at' => '2025-12-28 15:33:22',
            ],
            [
                'id' => 6,
                'customer_name' => 'SAJIDA Foundation',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'OTOBI Center, Level # 5, Plot # 12, Block CWC(C), Gulshan South Avenue, Gulshan-1, Dhaka.',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Fahad Aktar Habib',
                'commercial_contact_designation' => 'Asst. Coordinator, Admin-Procurement',
                'commercial_contact_email' => 'fahad@sajida.org',
                'commercial_contact_phone' => '01714944961',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:34:38',
                'updated_at' => '2025-12-28 15:34:38',
            ],
            [
                'id' => 7,
                'customer_name' => 'B-Trac Technologies Ltd',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'House# 68, Road# 11, Block# H, Banani, Dhaka-1213, Bangladesh.',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'F. M. Saeedduzzaman Siddiky',
                'commercial_contact_designation' => NULL,
                'commercial_contact_email' => 'saeed.siddiky@btractech.com',
                'commercial_contact_phone' => '01730387216',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:35:42',
                'updated_at' => '2025-12-28 15:35:42',
            ],
            [
                'id' => 8,
                'customer_name' => 'Cluster Technologies Ltd',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Plot No: 2/2, Road No: 01, Shyamoli, Dhaka-1207, Bangladesh.',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Rokonuzzaman',
                'commercial_contact_designation' => 'Senior Solution Architect',
                'commercial_contact_email' => 'rokon@clustechltd.com',
                'commercial_contact_phone' => '01974122221',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:36:42',
                'updated_at' => '2025-12-28 15:36:42',
            ],
            [
                'id' => 9,
                'customer_name' => 'BRAC-Aarong',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Aarong Center, 346, Tejgaon I/A, Dhaka-1208, Bangladesh.',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Rezwanul Hoque',
                'commercial_contact_designation' => 'Officer, Procurement',
                'commercial_contact_email' => 'rezwanul.hoque@brac.net',
                'commercial_contact_phone' => '01722885858',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:37:29',
                'updated_at' => '2025-12-28 15:37:29',
            ],
            [
                'id' => 10,
                'customer_name' => 'Service Hub Limited-001',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Plot 11, House 113/A, Gulshan 2, Dhaka – 1212',
                'bin_number' => '001558237-0101',
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Ashaduzzaman Asad',
                'commercial_contact_designation' => 'Managing Director',
                'commercial_contact_email' => 'Asad@servicehubltd.com',
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:38:29',
                'updated_at' => '2025-12-28 15:38:29',
            ],
            [
                'id' => 12,
                'customer_name' => 'Zara Business Solution',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => '1062, Ibrahimpur, Dhaka - 1206',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Nazrul Islam',
                'commercial_contact_designation' => NULL,
                'commercial_contact_email' => 'nazcse@gmail.com',
                'commercial_contact_phone' => '01725375050',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:48:39',
                'updated_at' => '2025-12-28 15:48:39',
            ],
            [
                'id' => 13,
                'customer_name' => 'Udvash-Unmesh Online Care',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Hossain Tower (5th Floor), 75, Green Road (Bir Uttam K.M. Shafiqul Road), Farmgate, Dhaka',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md Mehedy Hasan',
                'commercial_contact_designation' => 'DevOps Engineer',
                'commercial_contact_email' => 'mehedy@onnorokom.com',
                'commercial_contact_phone' => '01725021147',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:49:41',
                'updated_at' => '2025-12-28 15:49:41',
            ],
            [
                'id' => 14,
                'customer_name' => 'GiniLab',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Amchottor, Uttor Noudapara, Sapura, Rajshahi',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Muzahidul Islam',
                'commercial_contact_designation' => 'Managing Director',
                'commercial_contact_email' => 'muzahid.ginilab@gmail.com',
                'commercial_contact_phone' => '01715050937',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:51:06',
                'updated_at' => '2025-12-28 15:51:06',
            ],
            [
                'id' => 15,
                'customer_name' => 'Shurjomukhi Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Haque Tower(10th floor). JA 28/8/D Mohakhali C/A, Dhaka 1212',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Samiul Arif',
                'commercial_contact_designation' => 'Sr. System Administrator',
                'commercial_contact_email' => 'tanjim@shurjomukhi.com.bd',
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:51:53',
                'updated_at' => '2025-12-28 15:51:53',
            ],
            [
                'id' => 16,
                'customer_name' => 'ITL Bangladesh Pvt. Ltd',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'House 30, Lake Drive Road, Sector 7, Uttara, Dhaka-1230',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Nahianur Khan',
                'commercial_contact_designation' => 'IT Division',
                'commercial_contact_email' => 'nahianur.khan@itl-group.com.bd',
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:52:38',
                'updated_at' => '2025-12-28 15:52:38',
            ],
            [
                'id' => 17,
                'customer_name' => 'Best Business Bond Ltd',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => '46 Kazi Nazrul Islam Ave, Dhaka 1215',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Ashikur Rahman',
                'commercial_contact_designation' => 'Manager (Accounts & Admin)',
                'commercial_contact_email' => 'troyeebd@gmail.com',
                'commercial_contact_phone' => '01817566720',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:53:39',
                'updated_at' => '2025-12-28 15:53:39',
            ],
            [
                'id' => 18,
                'customer_name' => 'Zaynax Health & zDrop Bangladesh Ltd.',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Bashati Dream, Plot-03, Road-20, Level-05(C-5), Gulshan-1, Dhaka-1212',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'SM Mahadi Hasan Mukul',
                'commercial_contact_designation' => 'Tech Lead',
                'commercial_contact_email' => NULL,
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 1,
                'submitted_by' => 3,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:54:25',
                'updated_at' => '2025-12-28 15:54:25',
            ],
            [
                'id' => 19,
                'customer_name' => 'Esteem Soft Limited',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'House-77, Level-2, Road-2, Block-A, Bashundhara R/A, Dhaka-1229',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Ahmed Sharif',
                'commercial_contact_designation' => 'Director & CTO',
                'commercial_contact_email' => 'sharif@esteemsoftbd.com',
                'commercial_contact_phone' => '01844004900',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:55:19',
                'updated_at' => '2025-12-28 15:55:19',
            ],
            [
                'id' => 20,
                'customer_name' => 'Adorsho Pranisheba Ltd.',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => 'Haque Tower(10th floor). JA 28/8/D Mohakhali C/A, Dhaka 1212',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Nasir Uddin',
                'commercial_contact_designation' => 'Sr. System Administrator',
                'commercial_contact_email' => 'nasir@shurjomukhi.com.bd',
                'commercial_contact_phone' => '01913708051',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:56:21',
                'updated_at' => '2025-12-28 15:56:21',
            ],
            [
                'id' => 21,
                'customer_name' => 'Agrani Bank PLC',
                'customer_activation_date' => '2025-12-28',
                'customer_address' => '9/D Dilkusha Commercial Area, Dhaka-1000',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => 'Md. Niaz Morshed',
                'commercial_contact_designation' => 'Principal Officer,IT & MIS Division',
                'commercial_contact_email' => 'niaz@agranibank.org',
                'commercial_contact_phone' => '01790274699',
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 2,
                'submitted_by' => 1,
                'processed_by' => NULL,
                'created_at' => '2025-12-28 15:57:03',
                'updated_at' => '2025-12-28 15:57:03',
            ],
            [
                'id' => 23,
                'customer_name' => 'Loyal Communication',
                'customer_activation_date' => '2026-01-01',
                'customer_address' => 'Dhaka-1212, Gulshan-1',
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => NULL,
                'commercial_contact_designation' => NULL,
                'commercial_contact_email' => NULL,
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 1,
                'submitted_by' => 2,
                'processed_by' => NULL,
                'created_at' => '2025-12-29 12:34:46',
                'updated_at' => '2025-12-29 12:34:46',
            ],
            [
                'id' => 25,
                'customer_name' => 'ABC',
                'customer_activation_date' => '2026-01-01',
                'customer_address' => NULL,
                'bin_number' => NULL,
                'po_number' => NULL,
                'po_project_sheets' => '[]',
                'commercial_contact_name' => NULL,
                'commercial_contact_designation' => NULL,
                'commercial_contact_email' => NULL,
                'commercial_contact_phone' => NULL,
                'technical_contact_name' => NULL,
                'technical_contact_designation' => NULL,
                'technical_contact_email' => NULL,
                'technical_contact_phone' => NULL,
                'optional_contact_name' => NULL,
                'optional_contact_designation' => NULL,
                'optional_contact_email' => NULL,
                'optional_contact_phone' => NULL,
                'platform_id' => 1,
                'submitted_by' => 2,
                'processed_by' => 2,
                'created_at' => '2025-12-29 13:05:18',
                'updated_at' => '2025-12-29 13:05:18',
            ]
        ], ['id'], [
                'customer_name',
                'customer_activation_date',
                'customer_address',
                'bin_number',
                'po_number',
                'po_project_sheets',
                'commercial_contact_name',
                'commercial_contact_designation',
                'commercial_contact_email',
                'commercial_contact_phone',
                'technical_contact_name',
                'technical_contact_designation',
                'technical_contact_email',
                'technical_contact_phone',
                'optional_contact_name',
                'optional_contact_designation',
                'optional_contact_email',
                'optional_contact_phone',
                'platform_id',
                'submitted_by',
                'processed_by',
                'created_at',
                'updated_at',
        ]);
    }
}
